################################################### OWNER

#SAVE
POST https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/owner
Content-Type: application/json

{
  "firstName": "Alexandr",
  "lastName": "Dinaec",
  "passportNumber": "HB2911102",
  "phoneNumber": "+375291110033"
}

###

#UPDATE
PUT https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/owner/1
Content-Type: application/json

{
  "firstName": "Dmitro",
  "lastName": "Morgen",
  "passportNumber": "HB2911105",
  "phoneNumber": "+375291110033"
}

###

POST https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/owner/exchange
Content-Type: application/json

{
    "firstOwnerId": 1,
    "secondOwnerId": 2,
    "firstOwnerPetId": 1,
    "secondOwnerPetId": 5
}

###

#GET
GET https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/owner/1

###

#DELETE
DELETE https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/owner/1

###

#KILL
PUT https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/owner/kill/1

################################################### CAT

#SAVE
POST https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/pet/cat
Content-Type: application/json

{
  "ownerId": "1",
  "hasWool": "true",
  "age": "2",
  "breed": "Jone",
  "name": "Tuz"
}

###

#UPDATE
PUT https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/pet/cat/1
Content-Type: application/json

{
  "ownerId": "1",
  "hasWool": "false",
  "age": "11",
  "breed": "Jooone",
  "name": "Tuz"
}

###

#GET
GET https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/pet/cat/2

###

#DELETE
DELETE https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/pet/cat/2

###

########################################### DOG

#SAVE
POST https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/pet/dog
Content-Type: application/json

{
  "isTrained": "true",
  "age": "2",
  "breed": "Pec",
  "ownerId": "1",
  "name": "Dogger"
}

###

#UPDATE
PUT https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/pet/dog/2
Content-Type: application/json

{
  "isTrained": "false",
  "age": "2",
  "breed": "Pec",
  "ownerId": "1",
  "name": "Woody"
}

###

#GET
GET https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/pet/dog/1

###

#DELETE
DELETE https://spring-boot-pets.cfapps.eu10.hana.ondemand.com/pet/dog/2