################################################### OWNER

#SAVE
POST localhost:8080/owner
Content-Type: application/json

{
  "firstName": "Alexandr",
  "lastName": "Dinaec",
  "passportNumber": "HB2911102",
  "phoneNumber": "+375291110033"
}

###

#UPDATE
PUT localhost:8080/owner/1
Content-Type: application/json

{
  "firstName": "Dmitro",
  "lastName": "Morgen",
  "passportNumber": "HB2911105",
  "phoneNumber": "+375291110033"
}

###

POST localhost:8080/owner/exchange
Content-Type: application/json

{
    "firstOwnerId": 1,
    "secondOwnerId": 2,
    "firstOwnerPetId": 1,
    "secondOwnerPetId": 2
}

###

#GET
GET localhost:8080/owner/1

###

#DELETE
DELETE localhost:8080/owner/1

###

#KILL
PUT localhost:8080/owner/kill/1

################################################### CAT

#SAVE
POST localhost:8080/pet/cat
Content-Type: application/json

{
  "ownerId": "1",
  "hasWool": "true",
  "age": "2",
  "breed": "Jone",
  "name": "Tuz"
}

###

#UPDATE
PUT localhost:8080/pet/cat/1
Content-Type: application/json

{
  "ownerId": "1",
  "hasWool": "false",
  "age": "11",
  "breed": "Jone",
  "name": "Tuz"
}

###

#GET
GET localhost:8080/pet/cat/1

###

#DELETE
DELETE localhost:8080/pet/cat/1

###

########################################### DOG

#SAVE
POST localhost:8080/pet/dog
Content-Type: application/json

{
  "isTrained": "true",
  "age": "2",
  "breed": "Pec",
  "ownerId": "2",
  "name": "Dogger"
}

###

#UPDATE
PUT localhost:8080/pet/dog/2
Content-Type: application/json

{
  "isTrained": "false",
  "age": "2",
  "breed": "Pec",
  "ownerId": "1",
  "name": "Woody"
}

###

#GET
GET localhost:8080/pet/dog/1

###

#DELETE
DELETE localhost:8080/pet/dog/2